module.exports = {
  GAME_TICK_RATE: 120,
  PLAYER_SPEED: 15,
  MAX_LIVES: 1,
  GAME_WIDTH: 1280,
  GAME_HEIGHT: 720,
  INVINCIBILITY_DURATION: 2000,
  PLAYER_WIDTH: 80,
  PLAYER_HEIGHT: 80,
  PROJECTILE_RADIUS: 20,
  // New match system
  ROUNDS_PER_MATCH: 5,
  // Round transitions
  ROUND_END_DELAY: 2000,
  COUNTDOWN_DURATION: 3000,
}; 